import navbarDropdown from './modules/navbarDropdown';
import popularCervisesSwiper from './modules/swiper';
import answersSwiper from './modules/swiper';
import historySwiper from './modules/swiper';
import thisTab from './modules/thisTab';
import stickyHeader from './modules/stickyHeader';
import popularServices from './modules/main/popular-services';
import history from './modules/main/history';
import answer from './modules/main/answer';
